dmz0: 192.168.4.2
dmz1: 192.168.4.3
dmz2: 192.168.4.4
dmz3: 192.168.4.5
dmz4: 192.168.4.6
host0: 192.168.0.2
host1: 192.168.0.3
host2: 192.168.0.4
host3: 192.168.0.5
host4: 192.168.0.6
server0: 192.168.1.2
server1: 192.168.1.3
server2: 192.168.1.4
server3: 192.168.1.5
server4: 192.168.1.6
