admin_workstation: 192.168.0.7
dmz01: 192.168.2.2
dmz02: 192.168.2.3
dmz03: 192.168.2.4
dmz_jump_box: 192.168.2.5
server01: 192.168.1.2
server02: 192.168.1.3
server03: 192.168.1.4
user01: 192.168.0.2
user02: 192.168.0.3
user03: 192.168.0.4
